line-length = 120

# Skip ruff formatting for files in LLVM and other external projects
extend-exclude = ["interpreter/CppInterOp", "interpreter/llvm-project"]

[lint]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E4",
    "E7",
    "E9",
    # isort
    "I001"
]