name: Sync Cling repo

on:
  pull_request:
    paths:
      - 'interpreter/cling/**'
jobs:
  sync-cling-history:
    if: github.repository_owner == 'devajithvs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ROOT
        uses: actions/checkout@v4
        with:
          path: root
          fetch-depth: 524288

      - name: Checkout Cling
        uses: actions/checkout@v4
        with:
          repository: devajithvs/cling
          token: ${{ secrets.CLING_GIT_TOKEN_TESTING }}
          path: cling
          fetch-depth: 32768

      - name: Transfer changes between repositories
        run: |
         "root/.github/workflows/utilities/sync_cling.py"
